'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFRM_Paso05

    '''<summary>
    '''txtDetGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDetGiro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvGiro As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtReferencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferencias As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRef As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblConsulado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConsulado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUAjaxCons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUAjaxCons As Global.Subgurim.Controles.FileUploaderAJAX

    '''<summary>
    '''FUAjaxREMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUAjaxREMP As Global.Subgurim.Controles.FileUploaderAJAX

    '''<summary>
    '''grvFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvFiles As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtCompro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtn_si control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_si As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtn_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_no As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''NomprogSoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NomprogSoc As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProgRespSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgRespSocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rotDetprogSoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rotDetprogSoc As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DetprogSoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetprogSoc As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtProgSocDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgSocDet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfv2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfv2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btn_atras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_atras As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Seguir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Seguir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsjError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vlsmrPaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vlsmrPaso As Global.System.Web.UI.WebControls.ValidationSummary
End Class
