'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFRM_Paso02

    '''<summary>
    '''Rb_pjuridica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rb_pjuridica As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Rb_pJuridicaExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rb_pJuridicaExt As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Rb_pnaturalneg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rb_pnaturalneg As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Rb_orgestatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rb_orgestatal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Btn_Cancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Cancelar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Seguir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Seguir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsjError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjError As Global.System.Web.UI.WebControls.Label
End Class
