'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFRM_Paso08

    '''<summary>
    '''txtRstaMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRstaMP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_nacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_nacional As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chb_lima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_lima As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chb_provincias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_provincias As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_internacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_internacional As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chb_ams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_ams As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAms As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_amn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_amn As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAmn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_amcen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_amcen As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAmc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_eur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_eur As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtEur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEur As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_asia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_asia As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAsia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_afri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_afri As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAfr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAfr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chb_oceania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chb_oceania As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtOce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOce As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gViewDU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gViewDU As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Seguir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Seguir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsjError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vlatorSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vlatorSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''btn_load control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_load As Global.System.Web.UI.WebControls.Button
End Class
