'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfrm_DetalleSolicitud

    '''<summary>
    '''lblEstadoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstadoActual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEstado As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblRucEtiq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRucEtiq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_RUC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_RUC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkRuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRuc As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''txtRazonSoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRazonSoc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGiro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNameGiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNameGiro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDireccion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldpto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldpto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProv As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RotLicFunc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RotLicFunc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkLF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLF As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''RotNPartida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RotNPartida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPartida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartida As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRepresLegal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepresLegal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRepresentante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepresentante As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCgoRepre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCgoRepre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCgoRepres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCgoRepres As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RtoVigencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RtoVigencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkVP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkVP As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblDNI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDNI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdniRepr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdniRepr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkDNI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDNI As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblPContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPContacto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContacto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefono As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LUso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grvProd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvProd As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDocs As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grvProdRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvProdRef As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grvarcAdic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvarcAdic As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grvAplicUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvAplicUso As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtload As Global.System.Web.UI.WebControls.TextBox
End Class
