'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfrm_searchLic

    '''<summary>
    '''txt_razonsocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_razonsocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txt_RUC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_RUC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''uc_GiroSector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uc_GiroSector As Global.PromPeru.Web.Solicitudes.Client.uc_GiroSector

    '''<summary>
    '''Btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_buscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkExportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExportar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''grvSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvSolicitudes As Global.System.Web.UI.WebControls.GridView
End Class
